### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by agentscout101** [grebtsew/Discgolf#1]
Hello, I am currently building a disc golf simulator. Like a golf simulator where you hit the ball into a screen and it predicts the flight, except with a disc. I was wondering if I could contact you in some way to see if you would be interested in partnering with me. I have built the program, that detects the disc with a camera and can give all the information about the flight, but I need someone to create the game where it renders the disc's flight.

**Comment by grebtsew** [comment]
Hi @agentscout101 

This sounds like a really cool and interesting project. However I'm occupied with work and courses for the next few months. My plan is to update this project further in february 2022. Perhaps then I can help.

If you want to converse more you can reach me at daniel.grebtsew@gmail.com.
